language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t denisicun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true denisicun/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-course"
  env: "DockerReactCourse-env"
  bucket_name: "elasticbeanstalk-us-east-1-152486298439"
  bucket_path: "docker-react-course"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
