language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t denisicun/docker-react -f Dockerfil.dev .

script:
  - docker run -e CI=true denisicun/docker-react npm run test -- --coverage

